### ISSUE TITLE
What license is it?

### ISSUE THREAD

**Issue by Demetri0** [cudr/react-modal-promise#107]
Under what license is this library published?

Without license there is no way for users to use it (missing license file means that all right reserved for an author and nobody can use it)

**Comment by cudr** [comment]
@Demetri0 This library published under MIT license. There are [mark in package.json](https://github.com/cudr/react-modal-promise/blob/11d927927c3bf28d17c13789c3f9dca9e5d3aa5c/package.json#L35) about it.
