### ISSUE TITLE
handling of history back

### ISSUE THREAD

**Issue by dmitrydbelov** [cudr/react-modal-promise#11]
Is it possible to close all of  "promised" modals on history back?

**Comment by cudr** [comment]
Yes, sure.

You can execute .resolveAll() or .resolve(id) method from ModalContainer ref, or subscribe you modal, and resolve it on history change

**Comment by dmitrydbelov** [comment]
I have tried it, but  got a message:
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

so, just re-mounting of <ModalContainer/> works for now, as well as listening of history for every modal

**Comment by dmitrydbelov** [comment]
sorry - missed updated version ) it works
