### ISSUE TITLE
Trying to pass props from a Typescript component fails.

### ISSUE THREAD

**Issue by bassamanator** [cudr/react-modal-promise#132]
This is the TSX component that calls the modal:
![image](https://user-images.githubusercontent.com/61985779/168553363-cd9ee7e6-fe50-424c-81ff-d5c5d6ac207a.png)
```
TitleModal({ isOpen, currentTitle: 'hi' })
  .then(() => {})
  .catch(() => {});
```
Error message:
> (property) currentTitle: string
Argument of type '{ isOpen: boolean; currentTitle: string; }' is not assignable to parameter of type 'Omit<InstanceProps<any, any>, keyof InstanceProps<Resolve, Reject>> & Partial<InstanceProps<any, any>>'.
  Object literal may only specify known properties, and 'currentTitle' does not exist in type 'Omit<InstanceProps<any, any>, keyof InstanceProps<Resolve, Reject>> & Partial<InstanceProps<any, any>>'.ts(2345)

Using:
> "react": "^17.0.2", "react-modal-promise": "^1.0.2", "typescript": "^4.5.3"

**Comment by cudr** [comment]
@bassamanator, you should provide your modal component props, like: 
```tsx
const TitleModal = React.FC<{ ...your typed props }> = <></>
```

Please check new basic example
