### ISSUE TITLE
Can I rejectAll()?

### ISSUE THREAD

**Issue by andrewslock** [cudr/react-modal-promise#40]
Hi. I've got a request to add some functionality. I have a case where there's two buttons on a modal, the first one resolves with `true`, the second one with `false`. That way I can check what user clicked.
I simply do `if (await myModal())`
But sometimes I need to close the modals from outside. That can be achieved with method `resolveAll()`. The problem is, the modal is resolved as `undefined`, which is, of course, interpreted as `false`.
I could do something like 
`a = await myModal()`
`if (a === undefined)`
But it feels wrong.
I guess it would be much better if i could `rejectAll()` the promises and try to catch errors, instead of checking what promises return.
Unfortunately, there's no such a method. So my question is could you add this method?

**Comment by cudr** [comment]
@andrewslock Released as 0.6.0
