### ISSUE TITLE
Different types for onResolve and onReject?

### ISSUE THREAD

**Issue by adam1658** [cudr/react-modal-promise#59]
I've got a typescript promise component that should either resolve with a certain value, or reject with an `Error` object. But the types for this library say that `onResolve` and `onReject` both take the same type `T`.

The typescript types for `Promise.prototype.then` and `Promise.prototype.catch` show that the rejected callbacks take a different type to the resolved callback: https://github.com/microsoft/TypeScript/blob/cec2fda9a53620dc545a2c4d7b0156446ab145b4/lib/lib.es5.d.ts#L1446-L1461

Would you consider allowing different types for the argument to `onResolve` and `onReject` here?
https://github.com/cudr/react-modal-promise/blob/b7ce682483102fdf98a62c6ea7d37daa83f7069c/src/types.ts#L22-L32

Maybe something like this:
```ts
export interface InstanceProps<Result, RejectReason = Result> extends InstanceOptions { 
   //                                ^^^^^^^^^^^^^^^^^^^^^^^
   isOpen: boolean 
   instanceId: Hex 
   onReject: (reason?: RejectReason) => void 
   //                  ^^^^^^^^^^^^
   onResolve: (result?: Result) => void 
  
   /** @deprecated **/ 
   open: boolean 
   /** @deprecated **/ 
   close: (result?: Result) => void 
 } 
```

**Comment by cudr** [comment]
@adam1658 nice catch! 

Can you create PR with this update?
