### ISSUE TITLE
When opening new modal from another modal, the new modal isn't focusable.

### ISSUE THREAD

**Issue by talhabalaj** [cudr/react-modal-promise#76]
I am opening a modal, after than I have another modal which I open from the first modal. The new modal that is opened cannot be focused. Pressing Escape closing the first modal. If there are any input fields in the newer modal, they are not usable.

**Comment by cudr** [comment]
Hey, @talhabalaj. Can you attach reproduction link? You should fork any codesandbox example from readme.md.

**Comment by talhabalaj** [comment]
After more investigation, The issue was with the Modal library I was using, not this library.
